preset: laravel

enabled:
    - phpdoc_align
    - phpdoc_annotation_without_dot
    - phpdoc_link_to_see
    - concat_with_spaces
    - align_double_arrow
    - declare_strict_types

disabled:
    - phpdoc_to_comment
    - concat_without_spaces
