dist: trusty
sudo: required

language: php

php:
  - 7.1

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - composer self-update
  - composer install -d server --prefer-source --no-interaction --dev

script: phpunit --configuration server/phpunit.xml
