dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6

language: php

php:
  - 7.1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_script:
  - composer self-update
  - composer install -d server --prefer-source --no-interaction --dev

script: phpunit --configuration server/phpunit.php
