language: php

services:
  - mysql

php:
  - 7.1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_script:
  - composer self-update
  - composer install -d server --prefer-source --no-interaction --dev

script: phpunit
