options:
  formatter: stylish
files:
  include: '**/*.scss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: [1, { 'exclude': [] }]

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: [1, { 'allow-single-line-rulesets': false }]
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1
  property-units: [1, { 'global': ['rem', 'px', 's'] }]

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  class-name-format: [1, { 'allow-leading-underscore': false }]
  function-name-format: [1, { 'allow-leading-underscore': false }]
  id-name-format: [1, { 'allow-leading-underscore': false }]
  mixin-name-format: [1, { 'allow-leading-underscore': false }]
  placeholder-name-format: [1, { 'allow-leading-underscore': false }]
  variable-name-format: [1, { 'allow-leading-underscore': false }]

  # Style Guide
  bem-depth: 0
  border-zero: [1, { 'convention': none }]
  brace-style: [1, { 'allow-single-line': false }]
  clean-import-paths: 1
  empty-args: 1
  hex-length: [1, { 'style': short }]
  hex-notation: [1, { 'style': lowercase }]
  indentation: 1
  leading-zero: 1
  nesting-depth: [1, { 'max-depth': 4 }]
  property-sort-order: [1, { 'order': 'smacss' }]
  quotes: 1
  shorthand-values: [1, { 'allowed-shorthands': [1, 2] }]
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
